---
project_name: never
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: never
    main: ./cmd/never/main.go
    binary: never
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}

dockers_v2:
  - id: never
    ids:
      - never
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.description: "Wait for TCP, HTTP, and ICMP dependencies to become ready."
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "https://github.com/containeroo/never"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.url: "https://github.com/containeroo/never"
      org.opencontainers.image.version: "{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    images:
      - ghcr.io/containeroo/never
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
